config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users
  get 'mon-compte', action: :show, controller: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, :path => "jouets"
  resources :carts, :path => "panier"
  resources :carditems
  resources :charges
  post '/carditems/:id', to: 'carditems#create', as: 'panier'
  get '/histoire', to: 'static_pages#history'
  get '/contact', to: 'static_pages#contact'
  get '/commande/:id', to: 'carts#ask_email', as: 'commande'

  resources :items, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :cats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/associate_order_item.rb
class AssociateOrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/carditem.rb
class Carditem < ApplicationRecord
    belongs_to :item
    belongs_to :cart
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :carditems
    has_many :items, through: :carditems

    belongs_to :user
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true, length: { in: 3..20 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price, presence: true,  :inclusion => 0..1000

    has_one_attached :avatar

    has_many :carditems
    has_many :carts, through: :carditems

    has_many :associate_order_items
    has_many :order, through: :associate_order_items

    belongs_to :cat, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	after_create :order_send
	belongs_to :user
	has_many :associate_order_items
	has_many :item, through: :associate_order_items
	
	def order_send
		UserMailer.order_email(self).deliver_now
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send, :cart_update
  
  has_one :cart
  has_many :orders

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def cart_update
    cart_tmp = Cart.create()
    self.update(cart: cart_tmp)
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def create
        @item = Item.find(params[:item_id])
        @item.avatar.attach(params[:avatar])
        redirect_to(item_path(@item))
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find_by(user_id: params[:id])
  end

  def update
    @cart = find_cart
    @cart.update(carts_params)
    redirect_to @cart
  end

  def edit
    @cart = find_cart
  end

  def ask_email
    @cart = find_cart
    @order = Order.create(user_id: current_user.id)
    @cart.items.each do |item|
      AssociateOrderItem.create(order: @order, item: item)
    end
    @cart.items.destroy_all
  end

  private

  def carts_params
    params.require(:cart).permit(:adress, :adress_sup, :ville, :code)
  end

  def find_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end
  
  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.create(cats_params)

    if @cat.save
      redirect_to root_path, notice: "Nouvelle catégorie créée"
    else
      render :new
    end
  end

  def show
    @cat = find_cat
  end

  def edit
    @cat = find_cat
  end

  def update
    @cat = find_cat
    @cat.update(cats_params)
    redirect_to @cat
  end

  def destroy
    @cat = find_cat
    @cat.delete
    redirect_to '/', notice: "Catégorie supprimée"
  end

  private 

  def cats_params
    params.require(:cat).permit(:title)
  end

  def find_cat
    @cat = Cat.find(params[:id])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
before_action :authenticate_user!

  def new
   @user = current_user.email
   @amount = current_user.cart.items.pluck(:price).sum.to_f * 100
  end
  
  def create
    # Amount in cents
    @cart = current_user.cart
    @amount = @cart.items.pluck(:price).sum.to_f * 100
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    @order = Order.create(user_id: current_user.id)
    @cart.items.each do |item|
      AssociateOrderItem.create(order: @order, item: item)
    end
    @cart.items.destroy_all
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def edit
    @item = find_item
    @cat = Cat.find(params[:id])
  end

  def update
    @item = find_item
    @item.update(items_params)
    @item.errors
    redirect_to @item
  end

  def show
    @item = find_item
    @cat = @item.cat
  end

  def destroy
    @item = find_item
    @item.delete
    redirect_to '/', notice: "Produit supprimé"
  end

  def create
    @item = Item.create(items_params)
    if @item.save
      redirect_to @item, notice: "Nouveau produit créé"
    else
      render :new
    end
  end

  private

  def items_params
    params.require(:item).permit(:title, :description, :price, :avatar, :cat_id)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authenticate_user!, only: [:show]

  def show
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for_flash(type)
        case type
          when 'notice' then "alert-info"
          when 'success' then "alert-success"
          when 'error' then "alert-danger"
          when 'alert' then "alert-warning"
        end
    end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/carditems_helper.rb
module CarditemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/ask_email.html.erb
<div class="col">
        <div class="jumbotron mt-70" style="padding:0;">
            <div class="d-flex align-items-center h-100">
                <div class="container text-center py-5">
                <h3 class="mb-0">Un email vient d'etre envoyé</h3>
                <p class="mb-0">Veuillez attendre une réponse</p>
                </div>
            </div>
        </div>
    </div>

app/views/carts/edit.html.erb
<div class="container">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <%= form_for @cart do |f| %>
      <% if @cart.errors.any? %>
      <h4><%= pluralize(@cart.errors.count, "error") %> prevented this message from saving</h4>
        <ul>
          <% @cart.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
            <% end %>
        </ul>
        <% end %>
    <div class="form-group">
        <label>Adresse </label>
        <%= f.text_field :adress, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Adresse complementaire </label>
        <%= f.text_field :adress_sup, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Ville</label>
        <%= f.text_field :ville, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Code postale</label>
        <%= f.text_field :code, class: 'form-control'%>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Valider</button>
    </div>
    <% end %>
</div>

app/views/carts/show.html.erb
<div class="container my-4">
    <div class="row">
    <% if @cart.items.all.first == nil %>
    <div class="col">
        <div class="jumbotron mt-70" style="padding:0;">
            <div class="d-flex align-items-center h-100">
                <div class="container text-center py-5">
                <h3 class="mb-0">Votre pannier est vide</h3>
                <p class="mb-0">Ajoutez des produit à votre panier.</p>
                </div>
            </div>
        </div>
    </div>
    <% else %>
        <h1> Mon Panier: </h1>
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Delete</th>
                    </tr>
                </thead>
                <% @cart.price = 0%>
                <% @cart.items.each do |item_select|%>
                    <tbody>
                        <tr>
                            <% if item_select.avatar.attached? %>
                                <td><%= image_tag item_select.avatar, style: "width: 50px", :crop => :fill, class: "card-img-top" %></td>
                            <% else %>
                                <td><%= image_tag "https://pajulahti.com/wp-content/uploads/2017/04/500x500.jpeg", style: "width: 50px", :crop => :fill, class: "card-img-top" %></td>
                            <% end %>
                            <td><%= link_to item_select.title, item_path(item_select.id) %></td>
                            <td><%= item_select.description %></td>
                            <td><%= item_select.price %>€</td>
                            <td><%= link_to 'Delete', carditem_path(item_select), method: :delete%></td>
                            <% @cart.price = @cart.price + item_select.price%>
                        </tr>
                    </tbody>
                <% end%>
                <thead>
                    <tr>
                    <th>Price : <%= @cart.price %>€</th>
                    <th><%= link_to "Faire une demande à Alice", commande_path(@cart), class: "btn btn-primary" %></th>
                    </tr>
                </thead>
            </table>
    <% end %>
    </div>
</div>

app/views/cats/edit.html.erb
<h1 class="text-center">Modifier la catégorie</h1>
  <div class="container my-4">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <%= form_for @cat do |f| %>
        <% if @cat.errors.any? %>
        <h4><%= pluralize(@cat.errors.count, "error") %> prevented this message from saving</h4>
          <ul>
            <% @cat.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
              <% end %>
          </ul>
          <% end %>
      <div class="form-group">
          <label>Nom de la catégorie </label>
          <%= f.text_field :title, class: 'form-control'%>
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-primary">Valider</button>
      </div>
      <% end %>
  </div>

app/views/cats/index.html.erb
<main class="container my-4">
  <div class="row row-cols-4 row-cols-md-1 col-sm-12 p-md-0 m-md-0 d-flex justify-content-center">

  <% @cats.each do |cat| %>
    <div class="col-sm-12 col-12 col-md-4">
        <div class="card border-black mb-4 card-index">
          <div class="card-header p-0">
            Nom de la catégorie :<%= cat.title %>
          </div>
          <div class="card-footer">
            <%= link_to "Voir plus", cat_path(cat.id) , class:"btn btn-outline-secondary mx-1 my-1" %>
          </div>
        </div>
      </div>
    </a>
  <% end %>
  </div>
</main>

app/views/cats/new.html.erb
 <h1 class="text-center my-4">Créer une catégorie</h1>
 <div class="container mx-auto my-2 py-4">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= form_for @cat do |f| %>
    <div class="form-group">
      Nom de la catégorie<br />
      <%= f.text_field :title, class: 'form-control'%>
    </div>

    <div class="actions">
      <%= f.submit "Créer la catégorie", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/cats/show.html.erb
<div class="col col-md-6">
  <h1><%= @cat.title %></h1>
  <% if user_signed_in? && current_user.is_admin? %>
  <br><br><br><br><br><br><br>
  <%= link_to 'Supprimer', cat_path(@cat), class:"btn btn-danger btn-lg my-2 py-2 pl-2 pr-2 my-sm-0", method: "delete" %>
  <%= link_to 'Modifier', edit_cat_path(@cat), class:"btn btn-warning btn-lg my-2 py-2 pl-2 pr-2 my-sm-0" %>
<% end %>
</div>

app/views/items/edit.html.erb
<div class="container">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <%= form_for @item do |f| %>
      <% if @item.errors.any? %>
      <h4><%= pluralize(@item.errors.count, "error") %> prevented this message from saving</h4>
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
            <% end %>
        </ul>
        <% end %>
    <div class="form-group">
        <label>image </label>
        <%= f.file_field :avatar, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Titre de l'article </label>
        <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Catégorie de l'article </label>
        <%= f.select :cat_id, Cat.pluck(:title, :id), :prompt => 'Select One', class: 'form-control' %>
    </div>
    <div class="form-group">
        <label>Description de l'article</label>
        <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Prix</label>
        <%= f.text_field :price, class: 'form-control'%>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Valider</button>
    </div>
    <% end %>
</div>

app/views/items/index.html.erb
<%= render "layouts/banner"%>
<h2 class="text-center pb-4">Notre collection de jouets</h2>
<main class="container">
  <div class="row row-cols-4 row-cols-md-1 col-sm-12 p-md-0 m-md-0 d-flex justify-content-center">

  <% @items.each do |item| %>
    <div class="col-sm-12 col-12 col-md-4">
      <a href="<%= item_path(item.id) %>" class="card-clic">
        <div class="card border-black mb-4 card-index">
          <div class="card-header p-0">
            <% if item.avatar.attached? %>
              <%= image_tag item.avatar, :size => "400x350", :crop => :fill, class: "card-img-top" %>
            <% else %>
              <%= image_tag "https://pajulahti.com/wp-content/uploads/2017/04/500x500.jpeg", :size => "400x350", :crop => :fill, class: "card-img-top" %>
            <% end %>
          </div>
          <div class="card-body">
            <h4 class="card-title-product no-style-product mx-1 my-1"><%= item.title %><br><small class="float-right text-muted"><%= item.price %> €</small></h4>
          </div>
          <div class="card-footer">
            <%= link_to "Voir plus", item_path(item.id) , class:"btn btn-outline-secondary mx-1 my-1" %>
            <% if user_signed_in?%>
              <%= link_to panier_path(item), class: "color_cart", method: "POST" do %>
                <i class="fas fa-shopping-cart fa-lg float-right mt-3 mr-2"></i>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "color_cart", method: "GET" do %>
                <i class="fas fa-shopping-cart fa-lg float-right mt-3 mr-2"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </a>
  <% end %>
  </div>
</main>

app/views/items/new.html.erb
<div class="container">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <%= form_for @item do |f| %>
      <% if @item.errors.any? %>
      <h4><%= pluralize(@item.errors.count, "error") %> prevented this message from saving</h4>
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
            <% end %>
        </ul>
        <% end %>
    <div class="form-group">
        <label>image </label>
        <%= f.file_field :avatar, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Titre de l'article </label>
        <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Catégorie de l'article </label>
        <%= f.select :cat_id, Cat.pluck(:title, :id), :prompt => 'Select One', class: 'form-control' %>
    </div>
    <div class="form-group">
        <label>Description de l'article</label>
        <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Prix</label>
        <%= f.text_field :price, class: 'form-control'%>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Valider</button>
    </div>
    <% end %>
</div>

app/views/items/show.html.erb
<div class="jumbotron color-grey-light mt-70" style="padding:0;">
    <div class="d-flex align-items-center h-100">
        <div class="container text-center py-5">
          <h3 class="mb-0">Product page</h3>
        </div>
    </div>
</div>
<hr class="my-4 hr-jumbo">
<div class="container">	
    <div class="row">  
        <div class="col col-md-6">
            <% if @item.avatar.attached?%>
                <div class="m-b-25"> <%= image_tag @item.avatar, alt: 'avatar', :size => "500x500", :crop => :fill, class: "img-radius" %> </div>
            <% else %>
                <div class="m-b-25"> <img src="https://pajulahti.com/wp-content/uploads/2017/04/500x500.jpeg" class="img-radius" alt="User-Profile-Image"> </div>
            <% end %> 
        </div>
        <div class="col col-md-6">
            <h1><%=@item.title%></h1>
            <hr class="hr-product my-4">
            <span class="ml-2 font-weight-bold"><%=@item.price%> €</span>
            <br><br> 
            <p>Catégorie : <%=@item.cat.title%></h1><br>
            <p>Description : <%=@item.description%></h1><br>
            <p>Sélecteur de quantité</p><br>
            <% if user_signed_in? %>
            <div>
                <%= link_to panier_path(@item), class:"btn btn-outline-primary my-2 py-2 pl-2 pr-2 my-sm-0", method: "POST" do %>
                Ajouter au panier<span class="fas fa-shopping-cart ml-2"></span>
                <% end %>
            </div>
            <% end %>
            <% if user_signed_in? && current_user.is_admin? %>
            <br><br><br><br><br><br><br>
            <%= link_to 'Supprimer', item_path(@item), data: { confirm: "Êtes-vous sûr ?" }, class:"btn btn-danger btn-lg my-2 py-2 pl-2 pr-2 my-sm-0", method: "delete" %>
            <%= link_to 'Modifier', edit_item_path(@item), class:"btn btn-warning btn-lg my-2 py-2 pl-2 pr-2 my-sm-0" %>
        <% end %>
        </div>
    </div>	
</div>
<br><br><br><br><br>

app/views/users/show.html.erb
<div class="jumbotron color-grey-light mt-70" style="padding:0;">
    <div class="d-flex align-items-center h-100">
        <div class="container text-center py-5">
          <h3 class="mb-0">User profile</h3>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
    <% if @user.orders.all.first == nil %>
    <div class="col">
        <div class="jumbotron mt-70" style="padding:0;">
            <div class="d-flex align-items-center h-100">
                <div class="container text-center py-5">
                <h3 class="mb-0">Vous n'avez jamais effectuez de commande.</h3>
                <p class="mb-0">Vos futures commandes s'afficheront ici</p>
                </div>
            </div>
        </div>
    </div>
    <% else %>
        <h1> Past Order : </h1>
        <% @user.orders.reverse_each do |order|%>
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Price</th>
                    </tr>
                </thead>
                <% order.item.each do |item_select|%>
                    <tbody>
                        <tr>
                            <td><%= image_tag item_select.avatar, class: "card-img-top", style:"width: 50px" %></td>
                            <td><%= link_to item_select.title, item_path(item_select.id) %></td>
                            <td><%= item_select.description %></td>
                            <td><%= item_select.price %></td>
                        </tr>
                    </tbody>
                <% end%>
            </table>
        <% end%>
    <% end %>
    </div>
</div>