config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users
  get 'mon-compte', action: :show, controller: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, :path => "jouets"
  resources :carts, :path => "panier"
  resources :carditems
  resources :charges
  post '/carditems/:id', to: 'carditems#create', as: 'panier'
  get '/histoire', to: 'static_pages#history'
  get '/contact', to: 'static_pages#contact'
  get '/commande/:id', to: 'carts#ask_email', as: 'commande'

  resources :items, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :cats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/associate_order_item.rb
class AssociateOrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/carditem.rb
class Carditem < ApplicationRecord
    belongs_to :item
    belongs_to :cart
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :carditems
    has_many :items, through: :carditems

    belongs_to :user
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true, length: { in: 3..20 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price, presence: true,  :inclusion => 0..1000

    has_one_attached :avatar

    has_many :carditems
    has_many :carts, through: :carditems

    has_many :associate_order_items
    has_many :order, through: :associate_order_items

    belongs_to :cat, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	after_create :order_send
	belongs_to :user
	has_many :associate_order_items
	has_many :item, through: :associate_order_items
	
	def order_send
		UserMailer.order_email(self).deliver_now
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send, :cart_update
  
  has_one :cart
  has_many :orders

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def cart_update
    cart_tmp = Cart.create()
    self.update(cart: cart_tmp)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find_by(user_id: params[:id])
  end

  def update
    @cart = find_cart
    @cart.update(carts_params)
    redirect_to @cart
  end

  def edit
    @cart = find_cart
  end

  def ask_email
    @cart = find_cart
    @order = Order.create(user_id: current_user.id)
    @cart.items.each do |item|
      AssociateOrderItem.create(order: @order, item: item)
    end
    @cart.items.destroy_all
  end

  private

  def carts_params
    params.require(:cart).permit(:adress, :adress_sup, :ville, :code)
  end

  def find_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end
  
  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.create(cats_params)

    if @cat.save
      redirect_to root_path, notice: "Nouvelle catégorie créée"
    else
      render :new
    end
  end

  def show
    @cat = find_cat
  end

  def edit
    @cat = find_cat
  end

  def update
    @cat = find_cat
    @cat.update(cats_params)
    redirect_to @cat
  end

  def destroy
    @cat = find_cat
    @cat.delete
    redirect_to '/', notice: "Catégorie supprimée"
  end

  private 

  def cats_params
    params.require(:cat).permit(:title)
  end

  def find_cat
    @cat = Cat.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def edit
    @item = find_item
    @cat = Cat.find(params[:id])
  end

  def update
    @item = find_item
    @item.update(items_params)
    @item.errors
    redirect_to @item
  end

  def show
    @item = find_item
    @cat = @item.cat
  end

  def destroy
    @item = find_item
    @item.delete
    redirect_to '/', notice: "Produit supprimé"
  end

  def create
    @item = Item.create(items_params)
    if @item.save
      redirect_to @item, notice: "Nouveau produit créé"
    else
      render :new
    end
  end

  private

  def items_params
    params.require(:item).permit(:title, :description, :price, :avatar, :cat_id)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for_flash(type)
        case type
          when 'notice' then "alert-info"
          when 'success' then "alert-success"
          when 'error' then "alert-danger"
          when 'alert' then "alert-warning"
        end
    end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/carditems_helper.rb
module CarditemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_banner.html.erb
<div class="jumbotron-history">
  <div class="container mx-auto text-center">
    <h1 class="display-4 text-white">Les Lapins d'Alice</h1><br><br>
    <hr class="my-4 hr-jumbo">
    <p class="lead text-jumbo-big">Jeu et jouet enfant pour filles ou garçons, pour bébé ou pour toute la famille, découvrez le catalogue des lapins d'Alice</p>
    <p class="lead text-jumbo-big">Boutique de beaux jouets pour enfants de 0 à 10 ans. </p>
    <p class="lead">
      <a class="btn btn-secondary btn-lg" href="/histoire" role="button">Je découvre</a>
    </p>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
    <footer class="page-footer font-small unique-color-dark">

      <div class="bg-primary">
        <div class="container">

          <!-- Grid row-->
          <div class="row py-4 d-flex align-items-center">

            <!-- Grid column -->
            <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
              <h6 class="footer-title mb-0 text-footer">Connectez-vous avec nous sur les réseaux sociaux !</h6>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-6 col-lg-7 text-center text-md-right">

              <!-- Facebook -->
              <a class="fb-ic" href="https://fr-fr.facebook.com/leslapinsdalice/?ref=page_internal">
                <i class="fab fa-facebook-f text-footer mr-4 fa-lg"> </i>
              </a>
              <!--Instagram-->
              <a class="ins-ic" href="https://www.instagram.com/leslapinsdaliceparis/?hl=fr">
                <i class="fab fa-instagram text-footer fa-lg"> </i>
              </a>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row-->

        </div>
      </div>

      <!-- Footer Links -->
      <div class="container text-center text-md-left mt-5">

        <!-- Grid row -->
        <div class="row mt-3">

          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

            <!-- Content -->
            <h6 class="text-uppercase font-weight-bold">Mon Petit Chaton</h6>
            <hr class="bg-primary accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>Ici, vous trouverez des valeurs sures mais aussi et surtout de nouvelles marques, 
            bien souvent locales, fabriquées en France et responsables !</p>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

            <!-- Links -->
            <h6 class="text-uppercase font-weight-bold">Catalogue</h6>
            <hr class="bg-primary accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
              <a class="no-style" href="#!">Promotions</a>
            </p>
            <p>
              <a class="no-style" href="#!">Nouveaux produits</a>
            </p>
            <p>
              <a class="no-style" href="#!">Best Seller</a>
            </p>
            <p>
              <a class="no-style" href="#!">Tous nos produits</a>
            </p>

          </div>
          <!-- Grid column -->

          <!-- Grid column >
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

            <-- Links -->
            <!--h6 class="text-uppercase font-weight-bold">Aide</h6>
            <hr class="bg-primary accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
              <a class="no-style" href="#!">Votre compte</a>
            </p>
            <p>
              <a class="no-style" href="#!">Mentions légales</a>
            </p>
            <p>
              <a class="no-style" href="#!">Livraison</a>
            </p>
            <p>
              <a class="no-style" href="#!">FAQ</a>
            </p>

          </div>
          <-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

            <!-- Links -->
            <h6 class="text-uppercase font-weight-bold">Contact</h6>
            <hr class="bg-primary accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
              <i class="fas fa-home mr-3"></i> 22 rue Cler, Paris 75007</p>
            <p>
              <i class="fas fa-envelope mr-3"></i>boutique@leslapinsdalice.com</p>
            <p>
              <i class="fas fa-phone mr-3"></i> 01 45 51 54 21</p>

          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row -->

      </div>
      <!-- Footer Links -->

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2020 Copyright:
         Les Lapins d'Alice
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="fr" >
  <head>
    <meta charset="utf-8" />
    <title>Les Lapins d'Alice</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to "Les Lapins d'Alice", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= image_tag ("logo.jpg"), class: "logo" %>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Les Jouets
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/histoire">Notre Histoire</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          <% if user_signed_in? && current_user.is_admin?%>
          <li class="nav-item">
            <%= link_to "Ajouter un produit", new_item_path, :class =>"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ajouter une catégorie", new_cat_path, :class =>"nav-link" %>
          </li>
          <% end%>
        </ul>

        <% if current_user.present? %>
          <div class="nav-item">
            <%= link_to cart_path(current_user), :class =>"nav-link" do %>
              <span class="text-white">Mon Panier <i class="fas fa-shopping-cart fa-lg mr-2 text-footer"></i></span>
            <% end %>
          </div>          
        <% end %>

        <% if user_signed_in? %>
          <div class="nav-item dropdown">
              <button class="btn btn-secondary my-2 my-sm-0 dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="fa fa-user circle mr-1"></span> Mon compte</button>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "Mon profil", user_path(current_user.id), :class =>"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Éditer mon profil", edit_user_registration_path(current_user.id), :class =>"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class =>"dropdown-item" %>
              </div>
          </div>
         <% else %> 
          <div class="nav-item dropdown">
            <button class="btn btn-secondary my-2 my-sm-0 dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-user circle mr-1"></span> Sign up / Sign in</button>
            <div class="dropdown-menu">
              <%= link_to 'Créer son compte', new_user_registration_path, :class =>"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Se connecter', new_user_session_path, :class =>"dropdown-item" %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>
  </body>
</html>

app/views/layouts/_small_banner.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Mon Petit Chaton</h1>
    <p class="lead">Découvrez nos sublimes petits chatons! On ne peut pas y résister</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/litera/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gr51humlTz50RfCwdBYgT+XvbSZqkm8Loa5nWlNrvUqCinoe6C6WUZKHS2WIRx5o" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css" />
    <link rel="icon" href="https://www.favicon.cc/logo3d/822405.png" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>